name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Collect coverage
      run: |
        go get -tool github.com/dave/courtney@v0.4.4
        go tool courtney
      if: github.event_name == 'push'

    - uses: ncruces/go-coverage-report@v0
      with:
        coverage-file: coverage.out
        amend: true
      if: github.event_name == 'push'
